### ISSUE TITLE
Streamlit: Error running app.

### ISSUE THREAD

**Issue by djanjanin** [jalakoo/mock-graph-data-generator-streamlit#22]
It no worky. :-(
https://jalakoo-mock-graph-data-generator-mock-generatorsapp-clo-pcsqmw.streamlit.app/

**Comment by jalakoo** [comment]
Thanks @djanjanin, for some reason Streamlit cloud is unable to find the lastest [graph-data-generator](https://pypi.org/project/graph-data-generator/) package.

I'll post here as soon as I can resolve that.

**Comment by djanjanin** [comment]
Looks good. Please update the shortlink referenced @ https://neo4j.com/developer-blog/creating-web-synthetic-data/ and close this issue.
